import Head from 'next/head'
import Image from 'next/image';
import { useState, useContext } from 'react'
import { fetchApi } from '../../utils/handelApi';
import { Swiper, SwiperSlide } from 'swiper/react';
import { EffectCreative } from "swiper";
import 'swiper/css';
import "swiper/css/effect-creative";
import { cartContext } from '../../context/cartContext'
import { toast } from 'react-toastify';
import { baseUrl } from "../../utils/handelApi"
import OrderForm from './../../components/Forms/OrderForm';


function ProductUrl({ product }) {
  const { _id, name, price, newPrice, desc, image, typeAmount } = product;
  const { addToCart } = useContext(cartContext)
  const [amount, setAmount] = useState(1);

  const priceFinal = newPrice ? newPrice : price

  const orderInfo = {
    productId: _id,
    productName: name,
    productPrice: priceFinal,
    typeAmount: typeAmount,
    amount,
  }

  const handelProductToCart = () => {
    addToCart(orderInfo)
    toast.success('add product to cart  success', {
      position: toast.POSITION.BOTTOM_RIGHT,
    });
  }

  const increase = () => {
    if (amount < 10) {
      setAmount(amount + 1)
    } else {
      setAmount(amount)
    }
  }
  const decrease = () => {
    if (amount > 1) {
      setAmount(amount - 1)
    } else {
      setAmount(amount)
    }
  }

  return (
    <>
      <Head>
        <title>رحيق - {name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="product_details" dir="rtl">
        <div className="container">
          <div className="row">
            <div className="col-md-6 mb-4 order-2 order-md-1">
              <h1>
                {name}
              </h1>
              {newPrice
                ? <div className="price text-success pb-2 h5">
                  <span >{newPrice}</span>
                  -
                  <span className='text-danger text-decoration-line-through fw-ligh'>{price}</span>جنية
                </div>
                : <p className="price text-success pb-2 h5">{price} جنية</p>
              }
              <p className="desc mt-3 lead">
                {desc}
              </p>

              <div className="row g-2 mt-4">
                <strong className="fs-5 mb-3">اجمالي المطلوب دفعه: {amount * priceFinal + 50} جنيه</strong>
                <div className="w-100 d-flex align-items-center justify-content-between">
                  <button className='btn btn-success' onClick={increase} disabled={amount >= 10}>زود الكمية</button>
                  <p>{amount} {typeAmount}</p>
                  <button className='btn btn-danger' onClick={decrease} disabled={amount <= 1}>نقص الكمية</button>
                </div>
                <button className="btn btn-primary w-100" onClick={handelProductToCart}>
                  اضف الي السلة
                </button>
                <button className="btn btn-dark w-100 " data-bs-toggle="modal" data-bs-target="#exampleModal"
                >شراء المنتج الان
                </button>
              </div>

            </div>
            <div className="col-md-6 mb-4 order-1 order-md-2">
              <Swiper
                grabCursor={true}
                effect={"creative"}
                creativeEffect={{
                  prev: {
                    shadow: true,
                    translate: [0, 0, -400],
                  },
                  next: {
                    translate: ["100%", 0, 0],
                  },
                }}
                modules={[EffectCreative]}
                dir="ltr"
              >
                {image.map((el) => {
                  return (
                    <SwiperSlide key={el}>
                      <Image
                        layout="responsive"
                        width="600"
                        height="600"
                        src={`${baseUrl}/images/${el}`}
                        blurDataURL={`${baseUrl}/images/${el}`}
                        placeholder="blur"
                        alt="product" />
                    </SwiperSlide>
                    )
                })}
              </Swiper>
            </div>
          </div>
        </div>
      </section>

      <div className="modal fade show" id="exampleModal" tabIndex="-1" aria-hidden="true" dir="rtl">
        <div className="modal-dialog modal-lg modal-dialog-centered">
          <div className="modal-content show">
            <div className="modal-header">
              <h5 className="modal-title" id="exampleModalLabel">املئ البيانات من اجل طلب المنتج</h5>
              <button type="button" className="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div className="modal-body">
              <OrderForm orderInfo={[orderInfo]} fromCart={false} />
            </div>
          </div>
        </div>
      </div>

    </>
  )
}

export default ProductUrl

export async function getStaticPaths() {
  const { products } = await fetchApi(`products`);

  const paths = products.map(product => {
    return { params: { productUrl: product.url } }
  })

  return {
    paths,
    fallback: false
  }
}

export async function getStaticProps({ params }) {
  const { productUrl } = params;
  try {
    const { product } = await fetchApi(`product/${productUrl}`);
    return {
      props: {
        product,
      },
      revalidate: 10
    }
  } catch (error) {
    return {
      notFound: true,
      revalidate: 10
    }
  }
}