import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import HeroPages from '../../components/layout/HeroPages';
import ProductCard from '../../components/cards/ProductCard';
import HandelError from '../../components/HandelError';
import { fetchApi } from '../../utils/handelApi';


function Shop({ products, error }) {
  const { query } = useRouter()

  const productsList = () => {
    const productsMaping = products.map((product) => {
      return (
        <div className="col-12 col-sm-6 col-md-4 col-lg-4" key={product._id}>
          <ProductCard productData={product} />
        </div>
      )
    })
    
    if (products.length == 0 && !query.category) {
      return <HandelError image="bee-honey.png" text='لا يوجد منتجات علي الموقع الان' />
    } else if (products.length == 0) {
      return <HandelError image="bee-honey.png" text={`لا يوجد منتجات  ${query.category} الان`} />
    }
    else {
      return <div className="row g-3 mt-3">{productsMaping}</div>
    }
  }


  return (
    <>
      <Head>
        <title>رحيق - المتجر</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <HeroPages subTitle="المتجر الخاص بنا" title="كل المنتجات لدينا تجدها هنا" />
      <div className="py-5" dir="rtl">
        <div className="container">
          <div>
            <h4>انواع المنتجات</h4>
            <Link href="/shop" className={`btn ${!query.category ? 'btn-primary' : 'btn-outline-primary'}  me-1 mt-1`}>كل المنتجات</Link>
            <Link href="/shop/?category=عسل نحل" className={`btn ${query.category == 'عسل نحل' ? 'btn-primary' : 'btn-outline-primary'}  me-1 mt-1`}>عسل نحل</Link>
            <Link href="/shop/?category=خلطات صحية" className={`btn ${query.category == 'خلطات صحية' ? 'btn-primary' : 'btn-outline-primary'}  me-1 mt-1`}>خلطات صحية</Link>
            <Link href="/shop/?category=زيوت طبيعية" className={`btn ${query.category == 'زيوت طبيعية' ? 'btn-primary' : 'btn-outline-primary'}  me-1 mt-1`}>زيوت طبيعية</Link>
            <Link href="/shop/?category=منتجات نحل" className={`btn ${query.category == 'منتجات نحل' ? 'btn-primary' : 'btn-outline-primary'} mt-1`}>منتجات النحل</Link>
          </div>

          {error
            ? <HandelError image="server_down.svg" text="توجد مشكله في الخادم الان" />
            : productsList()
          }
        </div>
      </div>
    </>
  )
}

export default Shop

export async function getServerSideProps({ query }) {
  const category = query.category || null;
  try {
    const { products } = await fetchApi(`products${category ? `/${category}` : '/shop'}`);
    return {
      props: {
        products,
        error: null,
      },
    }
  } catch (error) {
    return {
      props: {
        products: [],
        error,
      },
    }
  }
}