import Head from 'next/head'
import HeroPages from '../../components/layout/HeroPages';
import ArticleCard from '../../components/cards/ArticleCard';
import HandelError from '../../components/HandelError';
import { fetchApi } from '../../utils/handelApi';

function Blog({ articles, error }) {

  // handel articles List 
  const articlesList = () => {
    const articlesMaping = articles.map((article) => {
      return (
        <div className="col-12 col-sm-6 " key={article._id}>
          <ArticleCard articleData={article} />
        </div>
      )
    })
    if (articles.length == 0) {
      return <HandelError image="bee-honey.png" text='لا يوجد مقالات علي الموقع الان' />
    }
    else {
      return <div className="row g-3 mt-3">{articlesMaping}</div>
    }
  }

  return (
    <>
      <Head>
        <title>رحيق - المقالات</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <HeroPages subTitle="كتباتنا" title="كل المقالات التي كتبنها عن العسل" />
      <div className="container blog  pt-4" dir="rtl">
        {error
          ? <HandelError image="server_down.svg" text="توجد مشكله في الخادم الان" />
          : articlesList()
        }
      </div>
    </>
  )
}

export default Blog

export async function getStaticProps() {
  try {
    const { articles } = await fetchApi(`articles`);
    return {
      props: {
        articles,
        error: null,
      },
      revalidate: 10
    }
  } catch (error) {
    return {
      props: {
        articles: [],
        error,
      },
      revalidate: 10
    }
  }
}