/* eslint-disable @next/next/no-sync-scripts */
import Head from 'next/head'
import Router from 'next/router'

import '../styles/bootstrap.rtl.min.css';
import '../styles/globals.css'
import 'react-toastify/dist/ReactToastify.css';
import NavBar from './../components/layout/NavBar';
import Footer from '../components/layout/Footer';
import CartContextProvider from '../context/cartContext';
import { ToastContainer } from 'react-toastify';
import NProgress from 'nprogress';

function MyApp({ Component, pageProps }) {

  Router.events.on("routeChangeStart",() => {
    NProgress.start();
  })
  Router.events.on("routeChangeComplete",() => {
    NProgress.done();
  })

  return (
    <>
      <Head>
        <title>رحيق</title>
        <meta name="description" content="Generated by create next app" />
        <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/nprogress/0.2.0/nprogress.min.css' integrity='sha512-42kB9yDlYiCEfx2xVwq0q7hT4uf26FUgSIZBK8uiaEnTdShXjwr8Ip1V4xGJMg3mHkUt9nNuTDxunHF0/EgxLQ==' crossOrigin='anonymous' referrerPolicy='no-referrer' />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastContainer />
      <CartContextProvider>
        <NavBar />
        <Component {...pageProps} />
        <Footer />
      </CartContextProvider>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
    </>
  )
}

export default MyApp
