import Head from 'next/head'
import Link from 'next/link'
import OrderForm from './../components/Forms/OrderForm';
import { useContext } from 'react'
import { cartContext } from './../context/cartContext'
function Cart() {
    const { cart, deleteCart } = useContext(cartContext)

    const cartlist = cart.map((el, idx) => {
        return (
            <tr key={el.id}>
                <td>{idx}</td>
                <th>{el.productName}</th>
                <td>{el.productPrice} جنيه</td>
                <td>{el.amount} {el.typeAmount}</td>
                <td>{el.amount * el.productPrice} جنيه</td>
                <td><button className="btn btn-danger btn-sm p-2" onClick={() => deleteCart(el.id)}>حذف</button> </td>
            </tr>
        )
    })
    return (
        <>
            <Head>
                <title>رحيق - سلة التسوق </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="container py-5" dir="rtl">
                {cart.length == 0
                    ?
                    <div className="alert alert-warning" role="alert">
                        سلة المشتريات فارغه  <Link href="/shop">تسوق المنتجات الان</Link>
                    </div> :
                    <div className="row">
                        <div className="col-md-5 card p-3 order-2">
                            <h5> املئ البيانات من اجل طلب المنتجات</h5>
                            <OrderForm orderInfo={cart} fromCart={true} />
                        </div>
                        <div className="col-md-7 order-1">
                        <h4>كل المنتجات التي توسقتها</h4>
                            <table className="table">
                                <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">المنتج</th>
                                        <th scope="col">السعر</th>
                                        <th scope="col">الكمية</th>
                                        <th scope="col">الاجمالي</th>
                                        <th scope="col">حذف</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {cartlist}
                                </tbody>
                            </table>
                        </div>
                    </div>
                }
            </div>
        </>
    )
}

export default Cart