import Head from 'next/head'
import Image from 'next/image'
import HeroPages from './../components/layout/HeroPages';
import ContactForm from './../components/forms/ContactForm';

function Contact() {
  return (
    <>
      <Head>
        <title>رحيق - اتصل بنا</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <HeroPages subTitle="تواصل معنا" title="تواصل معنا" />
      <section className="contact" dir="rtl" id="contact">
        <div className="container">

          <div className="row">
            <div className="col-md-6 mt-5">
              <ContactForm />
            </div>
            <div className="col-md-6 d-none d-md-flex">
              <Image src="/Contact-us.svg" layout="responsive" width="500" height="500" alt="message" />
            </div>
          </div>
        </div>
      </section>

    </>
  )
}

export default Contact