/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Image from 'next/image'
import ProductCard from './../components/cards/ProductCard';
import FeatureCard from './../components/cards/FeatureCard';
import ReviweCard from './../components/cards/ReviweCard';
import HeadSection from './../components/layout/HeadSection';
import ContactForm from '../components/forms/ContactForm';
import ArticleCard from './../components/cards/ArticleCard';
import { fetchApi } from './../utils/handelApi';
import HandelError from './../components/HandelError';
import { Swiper, SwiperSlide } from 'swiper/react';
import { EffectCreative } from "swiper";

import 'swiper/css';
import "swiper/css/effect-creative";

export default function Home({ products, articles, error }) {

  // handel products List 
  const productsList = () => {
    const productsMaping = products.map((product) => {
      return (
        <div className="col-12 col-sm-6 col-md-4 col-lg-4" key={product._id}>
          <ProductCard productData={product} />
        </div>
      )
    })
    if (products.length == 0) {
      return <HandelError image="bee-honey.png" text='لا يوجد منتجات علي الموقع الان' />
    }
    else {
      return <div className="row g-3 mt-3">{productsMaping}</div>
    }
  }

  // handel articles List 
  const articlesList = () => {
    const articlesMaping = articles.map((article) => {
      return (
        <div className="col-12 col-sm-6 " key={article._id}>
          <ArticleCard articleData={article} />
        </div>
      )
    })
    if (articles.length == 0) {
      return <HandelError image="bee-honey.png" text='لا يوجد منتجات علي الموقع الان' />
    }
    else {
      return <div className="row g-3 mt-3">{articlesMaping}</div>
    }
  }


  return (
    <div >
      <Head>
        <title>رحيق</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="d-flex align-items-center" dir="rtl" id="home">
        <div className="container">
          <div className="row">
            <div className="col-md-6 welcome d-flex align-items-center">
              <div>
                <h1 className="welcome-title">عسل رحيق انقي انواع العسل النحل</h1>
                <p className="welcome-desc lead mt-3">هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم
                  توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذ هذا النص هو مثال لنص يمكن
                  أن
                  يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل
                  هذ
                </p>
                <button className="btn btn-primary btn-lg mt-3">اتصل بنا الان</button>
              </div>
            </div>
            <div className="col-md-6 d-none d-md-flex">
              <img src="/honey cover (2).png" className="img" alt="" />

            </div>
          </div>
        </div>
      </header>
      <div className="overflow-hidden">
        <svg
          preserveAspectRatio="none"
          viewBox="0 0 1200 120"
          xmlns="http://www.w3.org/2000/svg"
          style={{ fill: '#e3ece3', width: '167%', height: 140, transform: 'scaleX(-1)' }}
        >
          <path
            d="M0 0v46.29c47.79 22.2 103.59 32.17 158 28 70.36-5.37 136.33-33.31 206.8-37.5 73.84-4.36 147.54 16.88 218.2 35.26 69.27 18 138.3 24.88 209.4 13.08 36.15-6 69.85-17.84 104.45-29.34C989.49 25 1113-14.29 1200 52.47V0z"
            opacity=".25"
          />
          <path
            d="M0 0v15.81c13 21.11 27.64 41.05 47.69 56.24C99.41 111.27 165 111 224.58 91.58c31.15-10.15 60.09-26.07 89.67-39.8 40.92-19 84.73-46 130.83-49.67 36.26-2.85 70.9 9.42 98.6 31.56 31.77 25.39 62.32 62 103.63 73 40.44 10.79 81.35-6.69 119.13-24.28s75.16-39 116.92-43.05c59.73-5.85 113.28 22.88 168.9 38.84 30.2 8.66 59 6.17 87.09-7.5 22.43-10.89 48-26.93 60.65-49.24V0z"
            opacity=".5"
          />
          <path d="M0 0v5.63C149.93 59 314.09 71.32 475.83 42.57c43-7.64 84.23-20.12 127.61-26.46 59-8.63 112.48 12.24 165.56 35.4C827.93 77.22 886 95.24 951.2 90c86.53-7 172.46-45.71 248.8-84.81V0z" />
        </svg>
      </div>


      <section className="about" dir="rtl" id="about">
        <div className="container">
          <HeadSection subTitle="من نحن" title="من نحن وما هي اهدافنا" />
          <div className="row">
            <div className="col-md-6 mt-3 order-2 order-md-1">
              <h2 className="fs-2  mt-4 mb-4">من نحن وما هي اهدافنا</h2>
              <p>هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من
                مولد النص العربى، حيث يمكنك أن تولد مثل هذ
                هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من
                مولد النص العربى، حيث يمكنك أن تولد مثل هذ</p>
              <p>هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من
                مولد النص العربى، حيث يمكنك أن تولد مثل هذ
                هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من
                مولد النص العربى، حيث يمكنك أن تولد مثل هذ</p>

            </div>
            <div className="col-md-6 mt-3 order-1 order-md-2">
              <div className="about-img bg-primary">
                <Image src="/beek.jpg" layout='responsive' width="335" height="335" className="img" alt="beek" />
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="services" dir="rtl">
        <div className="container">
          <HeadSection subTitle="ماذا نقدم لك" title="الخدمات التي نقدمها" />
          <div className="row">
            <div className="col-12 col-sm-6 col-lg-4 mt-3">
              <FeatureCard
                title="عسل نحل طبيعي"
                text="ذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذ"
                image="/icons/honey-60.png"
              />
            </div>
            <div className="col-12 col-sm-6 col-lg-4 mt-3">
              <FeatureCard
                title="خلطات صحيه"
                text="ذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذ"
                image="/icons/honey-64.png"
              />
            </div>
            <div className="col-12 col-sm-6 col-lg-4 mt-3">
              <FeatureCard
                title="منتجات عسل النحل"
                text="ذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذ"
                image="/icons/bumblebee-60.png"
              />
            </div>
            <div className="col-12 col-sm-6 col-lg-4 mt-3">
              <FeatureCard
                title="اجود انواع الزيوت"
                text="ذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذ"
                image="/icons/olive-oil-bottle-60.png"
              />
            </div>
            <div className="col-12 col-sm-6 col-lg-4 mt-3">
              <FeatureCard
                title="عروض علي المنتجات"
                text="ذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذ"
                image="/icons/offer-60.png"
              />
            </div>
            <div className="col-12 col-sm-6 col-lg-4 mt-3">
              <FeatureCard
                title="التوصيل السريع في مصر"
                text="ذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذ"
                image="/icons/delivery-60.png"
              />
            </div>
          </div>
        </div>
      </section>


      <section className="product" dir="rtl" id="product">
        <div className="container">
          <HeadSection subTitle="لدينا افضل منتجات" title="المتجر الخاص بنا" />
          {error
            ? <HandelError image="server_down.svg" text="توجد مشكله في الخادم الان" />
            : productsList()
          }
        </div>
      </section>

      <section className="blog" dir="rtl" id="produblogct">
        <div className="container">
          <HeadSection subTitle="كتباتنا" title="ماذا كتبتنا عن العسل النحل" />
          {error
            ? <HandelError image="server_down.svg" text="توجد مشكله في الخادم الان" />
            : articlesList()
          }
        </div>
      </section>


      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
        <path fill="#e3ece3ff" fillOpacity="1"
          d="M0,288L120,272C240,256,480,224,720,218.7C960,213,1200,235,1320,245.3L1440,256L1440,320L1320,320C1200,320,960,320,720,320C480,320,240,320,120,320L0,320Z">
        </path>
      </svg>
      <section className="testimonials" id="testimonials">
        <img className="img img-1" src="Asset-1.png" alt="" />
        <img className="img img-3" src="Asset-1.png" alt="" />

        <div className="container">
          <HeadSection subTitle="اراء العملاء" title="ماذا قال العملاء عن خدماتنا" />
          <div className="row justify-content-center">
            <div className="col-md-8 mt-4" >
              <Swiper
                grabCursor={true}
                effect={"creative"}
                creativeEffect={{
                  prev: {
                    shadow: true,
                    translate: [0, 0, -400],
                  },
                  next: {
                    translate: ["100%", 0, 0],
                  },
                }}
                modules={[EffectCreative]}
              >
                <SwiperSlide><ReviweCard /></SwiperSlide>
                <SwiperSlide><ReviweCard /></SwiperSlide>
              </Swiper>

            </div>
          </div>
        </div>
      </section>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
        <path fill="#e3ece3ff" fillOpacity="1"
          d="M0,32L120,48C240,64,480,96,720,96C960,96,1200,64,1320,48L1440,32L1440,0L1320,0C1200,0,960,0,720,0C480,0,240,0,120,0L0,0Z">
        </path>
      </svg>

      <section className="contact" dir="rtl" id="contact">
        <div className="container">
          <HeadSection subTitle="تواصل معنا" title="اتصل بنا في الحال" />
          <div className="row">
            <div className="col-md-6 mt-5">
              <ContactForm />
            </div>
            <div className="col-md-6 d-none d-md-flex">
              <Image src="/Contact-us.svg" layout="responsive" width="500" height="500" alt="message" />
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}


export async function getStaticProps() {
  try {
    const { products } = await fetchApi(`products/home`);
    const { articles } = await fetchApi(`articles/home`);
    return {
      props: {
        products,
        articles,
        error: null,
      },
      revalidate: 10
    }
  } catch (error) {
    return {
      props: {
        products: [],
        articles: [],
        error,
      },
      revalidate: 10
    }
  }
}