import Head from 'next/head'
import HeroPages from './../components/layout/HeroPages';
import ProductCard from './../components/cards/ProductCard';
import HandelError from './../components/HandelError';
import { fetchApi } from './../utils/handelApi';


function Offer({ products, error }) {
  const productsList = () => {
    const productsMaping = products.map((product) => {
      return (
        <div className="col-12 col-sm-6 col-md-4 col-lg-4" key={product._id}>
          <ProductCard productData={product} />
        </div>
      )
    })
    if (products.length == 0) {
      return <HandelError image="bee-honey.png" text='لا يوجد عروض علي الموقع الان' />
    }
    else {
      return <div className="row g-3 mt-3">{productsMaping}</div>
    }
  }



  return (
    <>
      <Head>
        <title>رحيق - العروض</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <HeroPages subTitle="العروض الخاص بنا" title="كل العروض لدينا تجدها هنا" />
      <div className="container pt-4" dir="rtl">
        {error
          ? <HandelError image="server_down.svg" text="توجد مشكله في الخادم الان" />
          : productsList()
        }
      </div>
    </>
  )
}

export default Offer


export async function getStaticProps() {
  try {
    const { products } = await fetchApi(`products/offer`);
    return {
      props: {
        products,
        error: null,
      },
      revalidate: 10
    }
  } catch (error) {
    return {
      props: {
        products: [],
        error,
      },
      revalidate: 10
    }
  }
}